### ISSUE TITLE
Update copy for requesting a custom map

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-mapping#14]
![screen shot 2015-10-13 at 3 52 11 pm](https://cloud.githubusercontent.com/assets/286171/10470525/a76626e2-71c2-11e5-9353-a00649b808e5.png)

We should adjust the copy on this as there are a couple grammatical/spelling errors and could use a bit more clarity. It appears to be the same on both maps.wsu.edu and beta.maps.wsu.edu right now.

My first suggestion is something like:

> Custom Map Request
>
> Name:
> Email:
> Department:
> Notes:
>
> Please provide as much detail as possible when submitting your request. We will contact you within X days with an update or any questions.
>
> Submit

I would also lean toward making Department a text field rather than a drop-down.

**Comment by jeremyBass** [comment]
not opposed to the suggestions.  I'll make some alterations shortly
