### ISSUE TITLE
Update copy for email sent after reporting an error

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-mapping#17]
> We just wanted to take this second to thank you again for taking the time to error the mapping issue. This email is to confirm that we have received the report and will be looking into it soon.

"to error the mapping issue" should be updated to match "report". I think we can shorten things up to be more readable in general.

Maybe:

> Thank you for taking the time to report an issue with WSU Maps. This email is to confirm that we have received your report and will be addressing it soon.

**Comment by jeremyBass** [comment]
yeps, cool thanks
