### ISSUE TITLE
BUG - Height of embed has grown alot

### ISSUE THREAD

**Issue by quantumJLBass** [washingtonstateuniversity/WSU-mapping#33]
per deec3cc 

Some where in this set of up date the maps we have implemented have gotten much taller then before.  I would think that 66% of the viewport over the 66% of the parent elements is the cause.  Original embeding design was a to be 66% in height of the containing area's width by default.  

Example of maps that are no long correctly sized is https://stage.police.wsu.edu/located-at/ but we have many in and out of wordpress that are being affected.  I'll create and issue too pointing here

![2016-11-29_1451](https://cloud.githubusercontent.com/assets/43837/20732413/73886634-b643-11e6-8598-492eebcbfde6.png)

**Comment by NateOwen** [comment]
Can you see if it's working better now?

**Comment by jeremyBass** [comment]
spot on now 👍 thank you

**Comment by jeremyBass** [comment]
small other issue, it is not responsive though, the aspect ratio is still not respected on resize as it was.

![image](https://cloud.githubusercontent.com/assets/43837/20761101/c4e7435e-b6d6-11e6-8652-a2d730ebef85.png)

**Comment by NateOwen** [comment]
Great, so far it's only your embed that has the fix.  I'll push it out to the rest.
