### ISSUE TITLE
jTrack error on map embed

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-mapping#5]
I'm seeing this error when maps are embedded on a page. I haven't dug into it to see if there's something I could be providing to the iframe.

![screen shot 2014-08-22 at 4 57 16 pm](https://cloud.githubusercontent.com/assets/286171/4018922/2e15e0fa-2a58-11e4-9654-949e23c8feb4.png)

**Comment by jeremyBass** [comment]
this was corrected over many updates
